"""Thin Python client for the ShardLoom CLI JSON protocol.

The package does not provide a native binding or fallback execution engine.
It invokes explicit ShardLoom CLI commands and parses their JSON envelopes.
"""

from .client import (
    ClaimGateCloseoutReport,
    ComputeCapabilityMatrix,
    ComputeCapabilityRow,
    CompatibilitySourcePlan,
    CompatibilitySourceSmokeReport,
    DEFAULT_COMPATIBILITY_SOURCE_SMOKE_INPUTS,
    ETL_INPUT_FORMATS,
    EngineCapabilityMatrix,
    EngineSelectionPlan,
    ExecutionEvidenceSlot,
    ExecutionResultEnvelopeView,
    HybridOverlayRunReport,
    LiveChangeContractPlan,
    LiveEtlReplayResult,
    LiveFixtureRunReport,
    LocalVortexPrimitiveSmokeReport,
    NativeUnsupportedCoverageRow,
    NativeVortexAdmissionLane,
    OperatorFamilyCoverageRow,
    PreparedVortexArtifacts,
    PredicateDtypeCoverageRow,
    PythonClientSmokeReport,
    RestApiContractPlan,
    RestApiDataPlane,
    RestApiDiscoveryContract,
    RestApiEventStream,
    RestApiLocalLifecycle,
    RestApiPlanPreview,
    RestApiSecurityGovernance,
    SemanticConformanceRow,
    SemanticConformanceSuite,
    ShardLoomClient,
    WorkloadCertificationDossier,
    WorkflowReadinessPlan,
    WorkflowReadinessSmokeReport,
)
from .context import (
    CapabilityPosture,
    CapabilityView,
    ContextCapabilities,
    DataFrameMethodCapability,
    DataFrameMethodCapabilityMatrix,
    ShardLoomContext,
    context,
)
from ._version import __version__
from .errors import (
    ShardLoomBinaryNotFoundError,
    ShardLoomCommandError,
    ShardLoomProtocolError,
)
from .models import Diagnostic, FieldEntry, FallbackStatus, OutputEnvelope
from .quickstart import QuickstartProofReport, quickstart_proof
from .query import (
    LazyFrame,
    UnsupportedWorkflowOperationReport,
    UnsupportedWorkflowReport,
    WorkflowCertificationReport,
    WorkflowOperation,
    WorkflowSource,
    from_arrow_ipc,
    from_arrow_table,
    from_pandas,
    GroupedLazyFrame,
    read_csv,
    read_json,
    read_parquet,
    read_vortex,
)

__all__ = [
    "__version__",
    "Diagnostic",
    "FallbackStatus",
    "FieldEntry",
    "OutputEnvelope",
    "QuickstartProofReport",
    "ClaimGateCloseoutReport",
    "ComputeCapabilityMatrix",
    "ComputeCapabilityRow",
    "DEFAULT_COMPATIBILITY_SOURCE_SMOKE_INPUTS",
    "ETL_INPUT_FORMATS",
    "EngineCapabilityMatrix",
    "EngineSelectionPlan",
    "ExecutionEvidenceSlot",
    "ExecutionResultEnvelopeView",
    "HybridOverlayRunReport",
    "LiveChangeContractPlan",
    "LiveFixtureRunReport",
    "CapabilityPosture",
    "CapabilityView",
    "DataFrameMethodCapability",
    "DataFrameMethodCapabilityMatrix",
    "CompatibilitySourcePlan",
    "CompatibilitySourceSmokeReport",
    "ContextCapabilities",
    "LiveEtlReplayResult",
    "LocalVortexPrimitiveSmokeReport",
    "NativeUnsupportedCoverageRow",
    "NativeVortexAdmissionLane",
    "OperatorFamilyCoverageRow",
    "PreparedVortexArtifacts",
    "PredicateDtypeCoverageRow",
    "PythonClientSmokeReport",
    "RestApiContractPlan",
    "RestApiDataPlane",
    "RestApiDiscoveryContract",
    "RestApiEventStream",
    "RestApiLocalLifecycle",
    "RestApiPlanPreview",
    "RestApiSecurityGovernance",
    "SemanticConformanceRow",
    "SemanticConformanceSuite",
    "ShardLoomClient",
    "WorkloadCertificationDossier",
    "WorkflowReadinessPlan",
    "WorkflowReadinessSmokeReport",
    "ShardLoomContext",
    "context",
    "quickstart_proof",
    "GroupedLazyFrame",
    "LazyFrame",
    "UnsupportedWorkflowOperationReport",
    "UnsupportedWorkflowReport",
    "WorkflowCertificationReport",
    "WorkflowOperation",
    "WorkflowSource",
    "from_pandas",
    "from_arrow_table",
    "from_arrow_ipc",
    "read_vortex",
    "read_csv",
    "read_json",
    "read_parquet",
    "ShardLoomBinaryNotFoundError",
    "ShardLoomCommandError",
    "ShardLoomProtocolError",
]
