"""Shared local runtime resource defaults for ShardLoom Python surfaces."""

DEFAULT_LOCAL_RUNTIME_MEMORY_GB = 4
DEFAULT_LOCAL_RUNTIME_MAX_PARALLELISM = 2
DEFAULT_INTERNAL_SMOKE_MEMORY_GB = 1
DEFAULT_INTERNAL_SMOKE_MAX_PARALLELISM = 1
