#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Validate v1 docs productization surfaces and generated support docs."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from release_report_utils import fail_closed_fields, read_text, require_markers, resolve_path, write_json
from write_v1_supported_unsupported_docs import (
    DEFAULT_OUTPUT as SUPPORTED_UNSUPPORTED_DOC,
)
from write_v1_supported_unsupported_docs import (
    DEFAULT_PACKAGE_MATRIX,
    DEFAULT_RUNS_TODAY,
    SCHEMA_VERSION as SUPPORTED_UNSUPPORTED_SCHEMA_VERSION,
)
from write_v1_supported_unsupported_docs import render as render_supported_unsupported


ROOT = Path(__file__).resolve().parents[1]
SCHEMA_VERSION = "shardloom.v1_docs_productization_report.v1"

DOC_MARKERS: dict[str, tuple[str, ...]] = {
    "README.md": (
        "docs/getting-started/source-checkout-install.md",
        "docs/getting-started/package-user-install.md",
        "docs/getting-started/troubleshooting-support.md",
        "docs/getting-started/v1-supported-unsupported.md",
    ),
    "docs/getting-started/install.md": (
        "Source Checkout Install",
        "Package User Install Status",
        "Troubleshooting And Support Bundle",
        "package_install_commands_visible=true",
    ),
    "docs/getting-started/source-checkout-install.md": (
        "source_checkout_install_v1=true",
        "cargo build -p shardloom-cli --bin shardloom",
        "python scripts\\release_dry_run_proof.py --rows 64 --iterations 1",
        "SHARDLOOM_BIN",
        "fallback_attempted=false",
    ),
    "docs/getting-started/package-user-install.md": (
        "package_channel_status=published_v0.1.0_selected_channels",
        "package_install_commands_visible=true",
        "python -m pip install shardloom==0.1.0",
        "brew install depsilon/tap/shardloom",
        "python -m pip uninstall -y shardloom",
        "public_package_claim_allowed=false",
    ),
    "docs/getting-started/troubleshooting-support.md": (
        "doctor --format json",
        "support-bundle --format json",
        "support_bundle_written=false",
        "fallback_attempted=false",
        "external_engine_invoked=false",
    ),
    "docs/getting-started/examples.md": (
        "stable_v1_example_local_csv",
        "stable_v1_example_local_jsonl",
        "stable_v1_example_local_parquet",
        "stable_v1_example_local_vortex",
        "stable_v1_example_prepare_vortex",
        "stable_v1_example_warm_prepared_query",
        "stable_v1_example_bounded_collect",
        "stable_v1_example_local_output_write",
        "stable_v1_example_evidence_inspection",
        "stable_v1_example_blocker_inspection",
        "unsupported_example_broad_sql",
        "unsupported_example_unbounded_collect",
        "unsupported_example_object_store",
        "unsupported_example_foundry",
        "unsupported_example_udf_effect",
    ),
    SUPPORTED_UNSUPPORTED_DOC.as_posix(): (
        SUPPORTED_UNSUPPORTED_SCHEMA_VERSION,
        "generated by scripts/write_v1_supported_unsupported_docs.py",
        "runs_today_schema_version=",
        "package_install_commands_visible=true",
        "unsupported_example_broad_sql",
        "fallback_attempted=false",
        "external_engine_invoked=false",
    ),
    "python/README.md": (
        "docs/architecture/v1-local-output-sink-scope.md",
        "Bounded materialization is explicit",
        "deterministic unsupported report",
    ),
    "website-src/src/pages/start.astro": (
        "source-checkout-install.md",
        "package-user-install.md",
        "v1-supported-unsupported.md",
        "package_install_commands_visible=true",
    ),
    "website-src/src/content/docs/field-guide/start-local-proof.mdx": (
        "source-checkout-install.md",
        "package-user-install.md",
        "v1-supported-unsupported.md",
    ),
    "website-src/src/content/docs/field-guide/python-surface.mdx": (
        "stable_v1_example_local_csv",
        "stable_v1_example_blocker_inspection",
        "unsupported_example_broad_sql",
    ),
}

FORBIDDEN_LIVE_PACKAGE_COMMANDS: tuple[str, ...] = (
    "cargo install shardloom",
    "conda install shardloom",
    "brew install shardloom",
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo-root", type=Path, default=ROOT)
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("target/v1-docs-productization-report.json"),
    )
    return parser.parse_args()


def load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def validate_generated_doc(repo_root: Path) -> list[str]:
    runs_today_path = resolve_path(repo_root, DEFAULT_RUNS_TODAY)
    package_matrix_path = resolve_path(repo_root, DEFAULT_PACKAGE_MATRIX)
    missing_inputs = [
        path
        for path in (runs_today_path, package_matrix_path)
        if not path.exists()
    ]
    if missing_inputs:
        return [
            f"{path.relative_to(repo_root).as_posix()}: missing generated-doc input"
            for path in missing_inputs
        ]
    runs_today = load_json(runs_today_path)
    package_matrix = load_json(package_matrix_path)
    expected = render_supported_unsupported(runs_today, package_matrix)
    actual = read_text(resolve_path(repo_root, SUPPORTED_UNSUPPORTED_DOC))
    if actual != expected:
        return [f"{SUPPORTED_UNSUPPORTED_DOC.as_posix()}: generated docs are stale"]
    return []


def build_report(repo_root: Path) -> dict[str, Any]:
    blockers: list[str] = []
    checked_docs: list[str] = []
    for rel_path, markers in DOC_MARKERS.items():
        text = read_text(resolve_path(repo_root, rel_path))
        blockers.extend(require_markers(rel_path, text, markers))
        checked_docs.append(rel_path)
        if rel_path.startswith("docs/getting-started/") or rel_path == "README.md":
            lower_text = text.lower()
            for command in FORBIDDEN_LIVE_PACKAGE_COMMANDS:
                if command in lower_text:
                    blockers.append(f"{rel_path}: forbidden live package command {command!r}")
    blockers.extend(validate_generated_doc(repo_root))
    return {
        "schema_version": SCHEMA_VERSION,
        "status": "passed" if not blockers else "failed",
        "checked_docs": checked_docs,
        "checked_doc_count": len(checked_docs),
        "generated_docs": [SUPPORTED_UNSUPPORTED_DOC.as_posix()],
        "claim_gate_status": "not_claim_grade",
        "blockers": blockers,
        **fail_closed_fields(),
    }


def main() -> int:
    args = parse_args()
    repo_root = args.repo_root.resolve()
    report = build_report(repo_root)
    write_json(resolve_path(repo_root, args.output), report)
    print(resolve_path(repo_root, args.output))
    return 0 if report["status"] == "passed" else 1


if __name__ == "__main__":
    raise SystemExit(main())
